export default {
  schedule: {
    day1: {
      hour0: "brew-it-over",
      hour1: "edi-film-club",
      hour9: "brew-it-over",
      hour10: "",
      hour11: "",
      hour12: "",
      hour13: "",
      hour14: "ovary-acting",
      hour15: "its-easy-being-green",
      hour16: "news-hub-show",
      hour17: "the-ellen-show",
      hour18: "",
      hour19: "gay-and-afraid",
      hour20: ""
    },
    day2: {
      hour9: "",
      hour10: "",
      hour11: "sports-hub-show",
      hour12: "isabel-s-world",
      hour13: "",
      hour14: "the-hour-of-power",
      hour15: "top-culture",
      hour16: "it-s-getting-hot",
      hour17: "",
      hour18: "sound-of-scotland",
      hour19: "",
      hour20: "edtalk"
    },
    day3: {
      hour9: "",
      hour10: "oh-what-a-wonderful-world",
      hour11: "",
      hour12: "808-s-hot-takes",
      hour13: "",
      hour14: "production-variety-show",
      hour15: "press-pause",
      hour16: "sonic-transcendence",
      hour17: "best-of-both-worlds",
      hour18: "",
      hour19: "",
      hour20: "the-midweek-toil"
    },
    day4: {
      hour9: "",
      hour10: "",
      hour11: "soundtrack",
      hour12: "",
      hour13: "",
      hour14: "arts-hub-show",
      hour15: "brown-time",
      hour16: "under-the-radar",
      hour17: "lacasa-culture",
      hour18: "down-to-earth-but-still-exceptional",
      hour19: "the-g-value",
      hour20: "electro-worldwide"
    },
    day5: {
      hour9: "",
      hour10: "",
      hour11: "",
      hour12: "the-mostly-indie-show",
      hour13: "alternate-current",
      hour14: "",
      hour15: "music-hub-show",
      hour16: "music-hub-show",
      hour17: "",
      hour18: "mixed-feelings",
      hour19: "pop-x-pop",
      hour20: "endless-summer"
    },
    day6: {
      hour9: "",
      hour10: "",
      hour11: "escape-to-the-country",
      hour12: "north-south-divide",
      hour13: "i-ll-try-anything-once",
      hour14: "hannah-s-happy-hour",
      hour15: "haters",
      hour16: "",
      hour17: "old-new-borrowed-blue",
      hour18: "eujo-s-jazz-hour",
      hour19: "easy-listening-with-em",
      hour20: "you-should-try"
    },
    day0: {
      hour9: "",
      hour10: "",
      hour11: "society-spotlight",
      hour12: "",
      hour13: "our-child",
      hour14: "mum-s-the-word",
      hour15: "poetry-but-make-it-relevant",
      hour16: "",
      hour17: "edi-film-club",
      hour18: "the-edventure-brief",
      hour19: "webster-s-dictionary",
      hour20: "asmarx"
    }
  }
};
